# GitHub workflow to automate the CI/CD for a Terraform module
name: Terraform Module CI/CD

on:
  # Runs on pushes and on pull requests targeting the default branch (main)
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow the workflow to create pull requests and releases using release please
permissions:
  contents: write
  id-token: write

# Define environment variables for Terraform version, working directory, and Cloud SDK version
env:
  TERRAFORM_VER: 1.14.0
  TERRAFORM_DIR: "."
  CLOUDSDK_VER: 548.0.0

jobs:
  # Build Job
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository code
      - name: Code checkout
        id: code_checkout
        uses: actions/checkout@v4

      # Setup the authentication for the Google Cloud using WIF
      - id: gcp_auth
        name: Authenticate to GCP
        uses: google-github-actions/auth@v3
        with:
          project_id: 'tidal-outlook-488409-e6'
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_ID }}

      # Install the specified version of Terraform CLI
      - id: tf_installation
        name: Terraform Installation
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VER }}

      # Install the specified version of Terraform CLI
      - name: Verify Terraform Version
        run: |
          terraform version

      # Run terraform tests for the module
      - name: Run Terraform Tests
        run: |
          terraform init
          terraform fmt -check -recursive
          terraform validate
          terraform test
